// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmuxP-4pb3TikN5f6ijVUyMqNKw9i7ibk',
    appId: '1:991373659022:web:ee4c77e79d26af2d86b2df',
    messagingSenderId: '991373659022',
    projectId: 'todo-968ff',
    authDomain: 'todo-968ff.firebaseapp.com',
    storageBucket: 'todo-968ff.firebasestorage.app',
    measurementId: 'G-66CKY8CS89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZgm89PJsOvw_82k8nYk77bgGL_4_EtU0',
    appId: '1:991373659022:android:fa7f1b953e1e5a5286b2df',
    messagingSenderId: '991373659022',
    projectId: 'todo-968ff',
    storageBucket: 'todo-968ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJsDxH6Wz6AUQnyVGhWjJXkJSBA9oDqM',
    appId: '1:991373659022:ios:fe36f0f89ca3d7d086b2df',
    messagingSenderId: '991373659022',
    projectId: 'todo-968ff',
    storageBucket: 'todo-968ff.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );
}
